#!/usr/bin/env ruby
# frozen_string_literal: true

def vim_key_bindings(prompt)
  prompt.on(:keypress) do |event|
    if event.value == 'j'
      prompt.trigger(:keydown)
    end
    if event.value == 'k'
      prompt.trigger(:keyup)
    end
    if event.value == 'h'
      prompt.trigger(:keyleft)
    end
    if event.value == 'l'
      prompt.trigger(:keyright)
    end
  end
end

def open_in_browser(url)
  Launchy.open(url)
end

def execute_ssh(bitnami_ip, instance)
  name = instance[:name]
  ipaddr = instance[:ipaddr]
  puts "\n\n~~~ sshing you into #{name} at #{ipaddr} ~~~"
  puts "use 'echo -en \"\\e[?25h\"' to unhide cursor\n\n"

  bitnami_ssh = "ssh -i ~/.ssh/Bridge_Data_Migration.pem -t bitnami@#{bitnami_ip} "
  instance_ssh = "\"ssh -i .ssh/Bridge_Data_Migration.pem -t ec2-user@#{ipaddr}\""

  system "echo 'echo -en \"\\e[?25h\"' | pbcopy"
  puts 'copied cursor command to clipboard'
  command = bitnami_ssh + instance_ssh
  exec(command)
end

def show_env_instances(mapping, environment)
  prompt = TTY::Prompt.new

  bitnami_ip = environment == 'production' ? '3.139.81.57' : '52.15.231.12'

  prompt.select('Select Instance') do |menu|
    vim_key_bindings(prompt)

    mapping
      .flatten
      .sort_by { |m| m[:name] }.select { |m| m[:environment] == environment }
      .each do |item| 
        menu.choice "#{item[:name]} - #{item[:ipaddr]}", -> { sub_menu(mapping, environment, bitnami_ip, item) }
      end
  end
end

def sub_menu(mapping, env, bitnami_ip, item)
  prompt = TTY::Prompt.new

  prompt.select('Make a selection') do |menu|
    vim_key_bindings(prompt)

    menu.choice 'Launch (opens in browser)', -> { open_in_browser(item[:url]) }
    menu.choice 'Open SSH Connection', -> { execute_ssh(bitnami_ip, item) }
    menu.choice 'Back', -> { show_env_instances(mapping, env) }
  end
end

def installing_missing_gems
  yield
rescue LoadError => e
  gem_name = e.message.split('--').last.strip
  install_command = "gem install #{gem_name}"

  # install missing gem
  puts "Probably missing gem: #{gem_name}"
  print 'Auto-install it? [yN] '
  gets.strip =~ /y/i or exit(1)
  system(install_command) or exit(1)

  # retry
  Gem.clear_paths
  puts 'Trying again ...'
  require gem_name
  retry
end

installing_missing_gems do
  require 'tty-prompt'
  require 'json'
  require 'launchy'
end

results = `aws-vault exec bridge-custom-dev -- aws ec2 describe-instances`

mapping = JSON(results)['Reservations'].map do |r|
  r['Instances'].map do |i|
    name = i['Tags'].select { |t| t['Key'] == 'Name' }.first['Value']
    eid = unless i['Tags'].select { |t| t['Key'] == 'elasticbeanstalk:environment-id' }.empty?
            i['Tags'].select { |t| t['Key'] == 'elasticbeanstalk:environment-id' }.first['Value']
          end
    env = name[/Staging/] ? 'staging' : 'production'
    ip = i['PrivateIpAddress']
    url = if eid
            "https://us-east-2.console.aws.amazon.com/elasticbeanstalk/home?region=us-east-2#/environment/dashboard?applicationName=#{name}&environmentId=#{eid}"
          end
    {
      environment: env,
      name: name,
      ipaddr: ip,
      url: url || nil
    }
  end
end

env_prompt = TTY::Prompt.new
env_prompt.select('Select Environment') do |env_menu|
  vim_key_bindings(env_prompt)

  env_menu.choice 'Production', -> { show_env_instances(mapping, 'production') }
  env_menu.choice ' Staging', -> { show_env_instances(mapping, 'staging') }
end
